title: Teaching
description: Resources for instructors and trainees.
show_downloads: true
google_analytics:
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
logo_url: 
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  back_url: https://julia-m-smith.github.io
  back_title: Home Page
  sc_url: https://scholar.google.com/citations?user=7Sy2fMYAAAAJ&hl=en&oi=ao
  sc_title: Google Scholar
  osf_url: https://osf.io/bc2ma/
  osf_title: OSF
  back_hide: false
  sc_hide: true
  osf_hide: true
